# Generated by Django 2.1.4 on 2018-12-31 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='password',
        ),
    ]
