# Generated by Django 2.1.4 on 2018-12-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_remove_article_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='password',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
