# Generated by Django 2.1.4 on 2019-01-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_auto_20190102_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='password',
            new_name='passwd',
        ),
    ]
