# Generated by Django 2.1.4 on 2019-01-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0007_auto_20190102_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='passwd',
            new_name='password',
        ),
    ]
